/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.metrichosu.restapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;

import java.util.Map;

@EnableAutoConfiguration(exclude = {
        DataSourceAutoConfiguration.class,
        DataSourceTransactionManagerAutoConfiguration.class,
        HibernateJpaAutoConfiguration.class
})
@SpringBootApplication
public class MetricHosuRestApiApplication {
    public static void main(String[] args) {
        SpringApplication app = new SpringApplication(MetricHosuRestApiApplication.class);
        app.setAdditionalProfiles("test");
        app.setDefaultProperties(Map.of("server.error.include-message", "always"));
        app.run();
    }
}
